# Project: StuGmSys
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../StuGmSys/main.o ../StuGmSys/StuSysFun.o
LINKOBJ  = ../StuGmSys/main.o ../StuGmSys/StuSysFun.o
LIBS     = -L"E:/new-2023/Dev-Cpp/TDM-GCC-64/lib" -L"E:/new-2023/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -pg
INCS     = -I"E:/new-2023/Dev-Cpp/TDM-GCC-64/include" -I"E:/new-2023/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/new-2023/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"E:/new-2023/Dev-Cpp/TDM-GCC-64/include" -I"E:/new-2023/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/new-2023/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"E:/new-2023/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = StuGmSys.exe
CXXFLAGS = $(CXXINCS) -pg -fexec-charset=gbk
CFLAGS   = $(INCS) -pg -fexec-charset=gbk
DEL      = E:\new-2023\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../StuGmSys/main.o: ../StuGmSys/main.cpp
	$(CPP) -c ../StuGmSys/main.cpp -o ../StuGmSys/main.o $(CXXFLAGS)

../StuGmSys/StuSysFun.o: ../StuGmSys/StuSysFun.cpp
	$(CPP) -c ../StuGmSys/StuSysFun.cpp -o ../StuGmSys/StuSysFun.o $(CXXFLAGS)
